#Config File

scoreboard:
  enabled: true
  title: "&6&lKing of the Hill"
  mode: "&7Mode: &3%mode%"
  king : "&7King: &4%player%"
  countdown: "&7Countdown: &6%time%"
  loc: "&7Loc: &ax:%x%, y:%y%"

# Only apply to CAPTURE mode
bossbar:
  king: "&6Capturing: &c%player%"
  no_king: "&6No King"

scheduler:
  # monday:
  #   "22:00": "koth_name"
  # tuesday:
  #   "22:00": "koth_name"
  wednesday:
    "22:00": "weekly_koth"
  # thursday:
  #   "22:00": "koth_name"
  # friday:
  #   "22:00": "koth_name"
  # saturday:
  #   "22:00": "koth_name"
  sunday:
    "22:00": "clan_koth"

rewards:
  weekly_koth: # Koth name
  - "give %player% diamond 1"
  # - any command
  clan_koth:
  - "give %player% diamond 1"

# Only if UniversalNotifier is installed
# This is usefull to send notificaions via telegram, discord or email
notifier:
  start: "⚔️ King Of the Hill **%name%** with mode **%mode%** has started!"
  end: "🤴 Koth **%name%** has ended - The new King is **%player%**!"