main: com.ar.askgaming.koth.KothPlugin
name: Koth
api-version: 1.21
version: 1.0
author: AMONLY
soft-depend: [BetterClans]
commands:
  koth:
    description: 'KOTH commands'
    usage: /<command> [args]

  
